name: unit

on:
  push:
    # branches: [master]
  pull_request: # run on all PRs, not just PRs to a particular branch

jobs:
  # `unit` includes just unit and proto tests.
  unit:
    strategy:
      fail-fast: false
      matrix:
        node: ['12', '14', '16']
    runs-on: ubuntu-latest
    name: node ${{ matrix.node }}
    env:
      LATEST_NODE: '16'

    steps:
    - name: git clone
      uses: actions/checkout@v2
      with:
        # Depth of at least 2 for codecov coverage diffs. See https://github.com/GoogleChrome/lighthouse/pull/12079
        fetch-depth: 2

    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - run: yarn install --frozen-lockfile --network-timeout 1000000
    - run: yarn jest audits/apple-touch-icon-test.js audits/audit-test.js audits/autocomplete-test.js audits/bootup-time-test.js audits/content-width-test.js audits/critical-request-chains-test.js audits/csp-xss-test.js audits/deprecations-test.js audits/diagnostics-test.js audits/errors-in-console-test.js audits/final-screenshot-test.js audits/font-display-test.js audits/image-aspect-ratio-test.js audits/image-size-responsive-test.js audits/installable-manifest-test.js audits/is-on-https-test.js audits/largest-contentful-paint-element-test.js audits/layout-shift-elements-test.js audits/long-tasks-test.js audits/main-thread-tasks-test.js audits/mainthread-work-breakdown-test.js audits/manual-audit-test.js audits/maskable-icon-test.js audits/metrics-test.js audits/network-requests-test.js audits/network-rtt-test.js audits/network-server-latency-test.js audits/no-unload-listeners-test.js audits/non-composited-animations-test.js audits/performance-budget-test.js audits/predictive-perf-test.js audits/preload-fonts-test.js audits/preload-lcp-image-test.js audits/redirects-http-test.js audits/redirects-test.js audits/resource-summary-test.js audits/screenshot-thumbnails-test.js audits/script-treemap-data-test.js audits/server-response-time-test.js audits/service-worker-test.js audits/splash-screen-test.js audits/themed-omnibox-test.js audits/third-party-facades-test.js audits/third-party-summary-test.js audits/timing-budget-test.js audits/unsized-images-test.js audits/user-timing-test.js audits/uses-rel-preconnect-test.js audits/uses-rel-preload-test.js audits/valid-source-maps-test.js audits/viewport-test.js page-functions-test.js
